## Code based on PyTorch Tensors example ##
### https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html ###

#### Sections:
- [Initializing a Tensor](#initialize)
- [Attributes of a Tensor](#attributes)
- [Operations on Tensors](#operations)
- [Bridge with NumPy](#bridge)
####

<a id="initialize"></a>
### Initializing a Tensor ###

In [ ]:
#Tensors: specialized data structure. Similar to numpy ndarray. Used to encode the inputs and otput of a model and mdel parameters.
#Tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data 
#Tensors are similar to numpy ndarrays but can run on GPU and have automatic differentiation capabilities.

import torch
import numpy as np

data = [[1, 2], [3, 4]]

#Initialize a tensor directly from data
x_data = torch.tensor(data)
print(x_data)
print(x_data.shape) #Print the shape of the tensor
print(x_data.dtype) #Print the datatype of the tensor
print("--------------- ---------------")


#Initialize a tensor from a NumPy array (and vice versa)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(x_np.shape) #Print the shape of the tensor
print(x_np.dtype) #Print the datatype of the tensor
print("--------------- ---------------")


#Initialize a tensor from another tensor
#The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor:  \n {x_ones} \n")
print("--------------- ---------------")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data!
print(f"Random Tensor: \n {x_rand} \n")


#Create a tensor with random or constant values
#shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

shape = (2, 3,) # shape of the tensor
rand_tensor = torch.rand(shape) # random tensor
ones_tensor = torch.ones(shape) # tensor of ones
zeros_tensor = torch.zeros(shape) # tensor of zeros
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")
print("--------------- ---------------")

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
--------------- ---------------
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
--------------- ---------------
Ones Tensor:  
 tensor([[1, 1],
        [1, 1]]) 

--------------- ---------------
Random Tensor: 
 tensor([[0.8320, 0.8260],
        [0.3319, 0.2687]]) 

