## Code based on PyTorch Tensors example ##
### https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html ###

#### Sections:
- [Initializing a Tensor](#initialize)
- [Attributes of a Tensor](#attributes)
- [Operations on Tensors](#operations)
- [Bridge with NumPy](#bridge)
####

<a id="initialize"></a>
### Initializing a Tensor ###

In [15]:
#Tensors: specialized data structure. Similar to numpy ndarray. Used to encode the inputs and otput of a model and mdel parameters.
#Tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data 
#Tensors are similar to numpy ndarrays but can run on GPU and have automatic differentiation capabilities.

import torch
import numpy as np

data = [[1, 2], [3, 4]]

#Initialize a tensor directly from data
x_data = torch.tensor(data)
print(x_data)


#Initialize a tensor from a NumPy array (and vice versa)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)


#Initialize a tensor from another tensor
#The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor:  \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data!
print(f"Random Tensor: \n {x_rand} \n")


#Create a tensor with random or constant values
#shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

shape = (2, 3,) # shape of the tensor
rand_tensor = torch.rand(shape) # random tensor
ones_tensor = torch.ones(shape) # tensor of ones
zeros_tensor = torch.zeros(shape) # tensor of zeros
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")
print("--------------- ---------------")

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
Ones Tensor:  
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1109, 0.1558],
        [0.9528, 0.5012]]) 

Random Tensor: 
 tensor([[0.1002, 0.8293, 0.4760],
        [0.6483, 0.4243, 0.1700]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

--------------- ---------------


<a id ="attributes"></a>
### Attributes of a Tensor ###


In [16]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


<a id="operations"></a>
### Operations on Tensors ###

In [17]:
#Over 1200 tensor operations, including transposing, indexing, slicing, mathematical operations (addition, multiplication), linear algebra, random sampling, and more are provided.
#By default, tensors are created on the CPU. Tensors can be moved to GPU using .to method

if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: mps:0


In [18]:
tensor = torch.ones(4, 4)
print(tensor)
print(f"First row of tensor: {tensor[0]}")
print(f"First column of tensor: {tensor[:, 0]}")
print(f"Last column of tensor: {tensor[..., -1]}")

tensor[:, 1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row of tensor: tensor([1., 1., 1., 1.])
First column of tensor: tensor([1., 1., 1., 1.])
Last column of tensor: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [20]:
#matrix multiplication
y1 = tensor @ tensor.T 
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

#element-wise multiplication
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
#single-element tensor
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


<a id="bridge"></a>
### Bridge with NumPy ###

In [ ]:
#Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [23]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [24]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
